### ISSUE TITLE
The project does not build on ubuntu server 20.04

### ISSUE THREAD

**Issue by andsh** [jluttine/dbus-listen#2]
When I try to build the project, I get the following:
`~/dbus-listen-0.1.0$ cabal build
Warning: The build command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-build command
or the legacy v1-build alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Config file path source is default config file.
Config file /home/andrey/.cabal/config not found.
Writing default configuration to /home/andrey/.cabal/config
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
[__0] trying: dbus-listen-0.1.0 (user goal)
[__1] next goal: base (dependency of dbus-listen)
[__1] rejecting: base-4.12.0.0/installed-4.1... (conflict: dbus-listen =>
base>=4.13 && <4.14)
[__1] fail (backjumping, conflict set: base, dbus-listen)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: dbus-listen, base
Trying configure anyway.
Configuring dbus-listen-0.1.0...
cabal: Encountered missing dependencies:
base ==4.13.*, dbus -any, optparse-applicative -any

andrey@www:~/dbus-listen-0.1.0$` 
```
How can I install the dependencies?

**Comment by jluttine** [comment]
Does it help if you run `cabal update` first as it suggests?

**Comment by andsh** [comment]
Hello
Sorry, I was not able to understand this language.
I have found a `C` implementation of the dbus API and solved my task.
So I'm closing the issue.
Answeering your question, the command `cabal update` did not find anything to be updated.
